var langs = {
    'en': {
        'code':'en',
        'ui_lang':'in english',
        'intro':'Flickr2GWToolset is a simple web application for transferring Flickr images to Wikimedia Commons via <a href="http://www.mediawiki.org/wiki/Help:Extension:GWToolset" target="_blank">GWToolset</a>. The focus is in editing metadata before uploading.  Only <a href="http://creativecommons.org/licenses/by/2.0/deed.fi" target="_blank">Attribution</a>, <a href="https://creativecommons.org/licenses/by-sa/2.0/deed.fi" target="_blank">ShareAlike</a> and "No known copyright restrictions" images are accepted.',
	    'all_remove_time':'Remove hours, minutes and seconds from all images',
	    'all_leave_year': 'Remove all except year',
	    'all_add_creator': 'Add Creator template to all authors',
	    'all_remove_creator': 'Remove Creator template from all authors',
	    'help_all_search_replace': 'Search and replace for selected field. Overwrite -option allows you to replace current value.',
	    'help_all_remove_time': 'Handy for historical images.',
	    'help_all_leave_year': 'Handy for historical images. See also <a href="http://commons.wikimedia.org/wiki/Template:date" target="_blank">date</a> and <a href="http://commons.wikimedia.org/wiki/Template:Other_date" target="_blank">Other date</a>.',
	    'header_batchtools': 'Batch metadata tools -- please remember, there is NO undo!',
	    'remove_time':'Remove hours etc.',
	    'leave_year':'Leave only year',
	    'flickralbumnro': 'What is the Flickr album number?',
	    'submit':'Fetch data from Flickr!',
	    'authors':'Authors',
	    'add_creator':'Add {{Creator:}}',
	    'remove_creator':'remove {{Creator:}}',
	    'add_institution':'Add {{Institution:}}',
	    'remove_institution':'Remove {{Institution:}}',
	    'titles':'Titles',
	    'search_template':'search template',
	    'descriptions':'Descriptions in different languages',
	    'depicted_people':'Who are these people?',
	    'depicted_place': 'Where was this photograph taken?',
	    'date':'When was this taken?',
	    'keeper': 'Who is keeping this image?',
	    'source_url': 'Where is image located (URL)?',
	    'accession_number':'Accession number',
	    'rights': 'Rights',
	    'preview': 'Preview in a new window',
	    'languages':{'en':'english'},
	    'desc_missing':'description missing',
	    'query_error':'Something went wrong in the query!',
	    'your_apikey':'Your Flickr api key',
	    'set_api_key':'You must provide a Flickr api key!'
	},
    'fi': {
        'code':'fi',
        'ui_lang':'suomeksi',
        'intro':'Flickr2GWToolset on yksinkertainen, selainpohjainen työkalu Flickr -albumien siirtämiseen <a href="http://www.mediawiki.org/wiki/Help:Extension:GWToolset" target="_blank">GWToolsetin</a> ymmärtämään muotoon. Tarkoitus on pelkän siirron sijasta antaa mahdollisuus parantaa metatietoja. Vain <a href="http://creativecommons.org/licenses/by/2.0/deed.fi" target="_blank">Attribution</a>, <a href="https://creativecommons.org/licenses/by-sa/2.0/deed.fi" target="_blank">ShareAlike</a> ja "No known copyright restrictions" kuvat otetaan huomioon.',
	    'all_remove_time':'Poista tunnit, minuutit ja sekunnit kaikista päivämäärä-kentistä',
	    'all_leave_year': 'Jätä pelkkä vuosiluku',
	    'all_add_creator': 'Lisää Creator-malline kaikkiin tekijöihin',
	    'all_remove_creator': 'Poista Creator-malline kaikista tekijöistä',
	    'help_all_search_replace': 'Valitse kenttä pudotusvalikosta, kopioi etsittävä teksti ensimmäiseen kenttää ja korvaava teksti toiseen kenttään. Voit myös syöttää arvoja tyhjiin kenttiin (esimerkiksi asettaa tekijän samaksi kaikille).',
	    'help_all_remove_time': 'Näppärä vanhojen kuvien kohdalla.',
	    'help_all_leave_year': 'Myös näppärä vanhojen kuvien kohdalla. Katso myös <a href="http://commons.wikimedia.org/wiki/Template:date" target="_blank">date</a> ja <a href="http://commons.wikimedia.org/wiki/Template:Other_date" target="_blank">Other date</a>.',
	    'header_batchtools': 'Työkaluja kaikkien metatietojen käsittelyyn',
	    'remove_time':'Poista tunnit, minuutit ja sekunnit',
	    'leave_year':'Jätä vain vuosi',
	    'flickralbumnro': 'Flickr-albuminumero',
	    'submit':'Hae kuvat Flickristä!',
	    'authors':'Tekijät',
	    'add_creator':'lisää {{Creator:}}',
	    'remove_creator':'poista {{Creator:}}',
	    'add_institution':'lisää {{Institution:}}',
	    'remove_institution':'poista {{Institution:}}',
	    'titles':'Otsikot',
	    'search_template':'etsi mallinetta',
	    'descriptions':'Kuvailut eri kielillä',
	    'depicted_people':'Ketä kuvassa on?',
	    'depicted_place': 'Missä se on otettu?',
	    'date':'Milloin?',
	    'keeper': 'Missä kuvaa säilytetään?',
	    'accession_number':'Kokoelmanumero',
	    'source_url': 'Mistä kuva on peräisin (URL)?',
	    'rights': 'Oikeudet',
	    'preview': 'Esikatselu uudessa ikkunassa',
	    'languages':{'fi':'suomeksi','sv':'ruotsiksi','en':'englanniksi'},
	    'desc_missing':'kuvaus puuttuu!',
	    'query_error':'Jotain meni pieleen kyselyssä!',
	    'your_apikey':'Flickr API-avaimesi',
	    'set_api_key':'Sinun täytyy antaa Flickerin API-avain!'
	}
}
